<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>HKW.HKWUtilsTests</RootNamespace>
    <Configurations>Debug;Release</Configurations>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <StartupObject>HKW.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ReactiveUI" Version="23.2.27" />
    <PackageReference Include="HKW.ReactiveUI" Version="0.4.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HKW.Utils\HKW.Utils.csproj" />
  </ItemGroup>
</Project>
