<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>1.4.0</Version>
    <Authors>HKW</Authors>
    <Company>HKW</Company>
    <PackageDescription>Utils by HKW.</PackageDescription>
    <PackageTags>MVVM;ReactiveUI;Observable;Collection;FilterCollection;NumberUtils;Extensions;EnumInfo</PackageTags>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RootNamespace>HKW.HKWUtils</RootNamespace>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <PropertyGroup>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PathMap Condition="'$(SolutionDir)' != ''">$(SolutionDir)=/_/</PathMap>
    <PathMap Condition="'$(SolutionDir)' == ''"
      >$(MSBuildProjectDirectory)=/_/$(AssemblyName)/</PathMap
    >
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
</Project>
